// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceBindingMetadata service binding metadata
//
// swagger:model ServiceBindingMetadata
type ServiceBindingMetadata struct {

	// expires at
	ExpiresAt string `json:"expires_at,omitempty"`

	// renew before
	RenewBefore string `json:"renew_before,omitempty"`
}

// Validate validates this service binding metadata
func (m *ServiceBindingMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service binding metadata based on context it is used
func (m *ServiceBindingMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceBindingMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceBindingMetadata) UnmarshalBinary(b []byte) error {
	var res ServiceBindingMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
